#!/usr/bin/env bash

# make callable from anywhere
cd "$( dirname "${BASH_SOURCE[0]}" )" || exit 1


# stolen from:
# https://hackernoon.com/how-to-create-a-simple-bash-shell-script-to-send-messages-on-telegram-lcz31bx


GROUP_ID=$(cat "${2:-"todo_group.id"}")
disable_notification=${3:-"false"}
BOT_TOKEN=$(cat "TOKEN")

# this 3 checks (if) are not necessary but should be convenient
if [ "$1" == "-h" ]; then
    echo "Usage: $(basename "$0") \"text message\" group.id [disable_notification] [[message_thread_id]]"
    exit 0
fi

if [ -z "$1" ]
  then
    echo "Add message text as second arguments"
    exit 0
fi

if [ "$#" -gt 4 ]; then
    echo "You can pass only four arguments. For string with spaces put it on quotes"
    exit 0
fi

text=${1}
echo
echo "$text"
echo
text=${text//\*/\\\*}
text=${text//\[/\\\[}
text=${text//\]/\\\]}
text=${text//\(/\\\(}
text=${text//\)/\\\)}
text=${text//~/\\~}
# text=${text//\`/\\\`}  # works, but is not desired, since actual gravis is syntax for code highlighting
text=${text//>/\\>}
# text=${text//"\#"/"\\#"}
# text=${text//\+/\\\+}  # WTF
text=${text//\+/\±}
text=${text//\-/\\\-}
text=${text//=/\\=}
text=${text//|/\\|}
text=${text//\{/\\\{}
text=${text//\}/\\\}}
text=${text//./\\.}
text=${text//!/\\!}

echo "$text"
echo
echo
if [ -z "$4" ]
  then
    curl -s --data "text=${text}" --data "chat_id=$GROUP_ID" --data "parse_mode=MarkdownV2" --data "disable_notification=$disable_notification" 'https://api.telegram.org/bot'$BOT_TOKEN'/sendMessage' # > /dev/null
else
    curl -s --data "text=${text}" --data "chat_id=$GROUP_ID" --data "parse_mode=MarkdownV2" --data "disable_notification=$disable_notification" --data "message_thread_id=$4" 'https://api.telegram.org/bot'$BOT_TOKEN'/sendMessage' # > /dev/null
fi

sleep 1
