#!/usr/bin/env bash

# make callable from anywhere
cd "$( dirname "${BASH_SOURCE[0]}" )"


# stolen from:
# https://hackernoon.com/how-to-create-a-simple-bash-shell-script-to-send-messages-on-telegram-lcz31bx


GROUP_ID=$(cat ${2:-"todo_group.id"})
BOT_TOKEN=$(cat "TOKEN")

# this 3 checks (if) are not necessary but should be convenient
if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` \"text message\""
  exit 0
fi

if [ -z "$1" ]
  then
    echo "Add message text as second arguments"
    exit 0
fi

if [ "$#" -gt 2 ]; then
    echo "You can pass only two arguments. For string with spaces put it on quotes"
    exit 0
fi

text=${1}
text=${text//>/\\>}
text=${text//-/\\-}
curl -s --data "text=${text}" --data "chat_id=$GROUP_ID" --data "parse_mode=MarkdownV2" 'https://api.telegram.org/bot'$BOT_TOKEN'/sendMessage' # > /dev/null

sleep 1
